[package]
name = "day2"
version = "0.1.0"
authors = ["justin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measure_time = "0.6"
hex = "0.4.2"